import { atom } from "recoil";

export const UserListData = atom({
  key : "updatedListUser" ,
  default : [
    {
        UserName : "ashar90" ,
        FirstName : "Ashar",
        LastName : "Ahmad",
        Password : "12asAs",
        ConfirmPassword : "12asAs",
        Image : "https://i.redd.it/buji69fnjbs21.jpg",
        Address : "Purana Bazar" ,
        Country : "India",
        State : "Jharkhand",
        City : "Dhanbad",
        Email : "ashar90@gmail.com",
        Gender : "Other",
        DOB : "21.09.1997",
        PhoneNUmber : "+91 7779995915",
        id : 0
    },
    {
        UserName : "harshit90" ,
        FirstName : "Harshit",
        LastName : "Mishra",
        Password : "12asAs",
        ConfirmPassword : "12asAs",
        Image : "https://www.coomz.net/wp-content/uploads/2018/06/Cutie-pie-800w.jpg",
        Address : "Naya Bazar" ,
        Country : "India",
        PhoneNUmber : "+91 70090959545",
        State : "U.P",
        City : "Kanpur",
        Email : "harshit@gmail.com",
        Gender : "Female",
        DOB : "01.09.2000",
        Zipp : "234990",
        id : 1
    },
    {UserName : "subhali3" ,
    FirstName : "Subhali",
    LastName : "Shah",
    Password : "12asAs",
    ConfirmPassword : "12asAs",
    Image : "https://i.redd.it/9f3x2yy3op031.jpg",
    Address : "G T Road" ,
    Country : "India",
    PhoneNUmber : "+91 9787874334",
    State : "Chattisgarh",
    City : "Indore",
    Email : "subhi@gmail.com",
    Gender : "Female",
    DOB : "14.05.2002",
    Zipp : "011090",
    id : 2
    }
    ,
    {
        UserName : "ritu22" ,
        FirstName : "Ritu",
        LastName : "Jaiswal",
        Password : "12asAs",
        ConfirmPassword : "12asAs",
        Image : "https://tse1.mm.bing.net/th?id=OIP.B7H_cSXgEunLgbTNaE-AEgHaJM&pid=Api&P=0",
        Address : "KT road" ,
        PhoneNUmber : "+91 6784676333",
        Country : "India",
        State : "U.P",
        City : "Jhansi",
        Email : "ritu22@gmail.com",
        DOB : "22.11.1999",
        id : 3,
        Gender : "Female",
        Zipp : "890890"
    
    },
    {
        UserName : "abhi89" ,
        FirstName : "Abhishek",
        LastName : "Raz",
        Password : "12asAs",
        ConfirmPassword : "12asAs",
        Image : "https://cdn.quotesgram.com/img/83/64/1175668991-502f64367ce272070b597bd2eb35a06a.jpg",
        Address : " Mango" ,
        Country : "India",
        State : "Jharkhand",
        PhoneNUmber : "+91 8889936333",
        City : "Ranchi",
        Email : "abhi89@gmail.com",
        Gender : "Other",
        DOB : "23.02.1998",
        id : 4,
        Zipp : "992770"
    
    },
    {
        UserName : "abhikumar9" ,
        FirstName : "Abhishek",
        LastName : "Kumar",
        Password : "12asAs",
        ConfirmPassword : "12asAs",
        Image : "https://i.redd.it/gwo6kiaelmb21.jpg",
        Address : "Lal kuwa" ,
        Country : "India",
        State : "Jharkhand",
        PhoneNUmber : "+91 897766333",
        City : "Palamo",
        Email : "abhikumar9@gmail.com",
        Gender : "Other",
        DOB : "16.08.2003",
        id : 5,
        Zipp : "0909090",
    }
]
})

